"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_API_PERSONAL_TOKEN"
"base_path": "."
"base_url": "https://openmindtech.api.crowdin.com"

"preserve_hierarchy": true

files: [
  {
    "source": "/ToolpathAnalyser/files/language/*.ts",
    "translation": "/ToolpathAnalyser/files/language/%file_name%.%locale%.%file_extension%"
  }
]